In [1]:
pip install transformers torch numpy gudhi -q

Note: you may need to restart the kernel to use updated packages.


In [2]:
text = ["בחופשה האחרונה שלנו, נסענו להכיר את היופיים של מדבר הנגב. בין אם מדובר בצוקים המרשימים, בחי הבר המיוחד, או בשקט המוחלט, יש משהו מאוד מיוחד במדבר. אחת החוויות המרגשות ביותר שלנו הייתה לצפות בזרחת השמש מעל המדבר. האור המתפשט מאחורי ההרים, השמים המשתנים מאוד מהיר מאופל לתכלת, והשלווה המוחלטת שאפשר רק במדבר, הכל הפך את החוויה לבלתי נשכחת", 
          
          "במהלך שנת הלימודים הראשונה שלי באוניברסיטה, הצטרפתי לקבוצת טיול שהגיעה להר האייפל. למרות הקור החודר, הייתי מחויב לעלות לפסגה בכל בוקר, כדי לצפות בזרחת השמש מעל פריס", 
          
          "הייתי מתעורר בבוקר מוקדם, לפני כולם, כדי לצפות בזרחת השמש. היו ימים שהשמים היו מלאים בגוונים של ורוד וכתום, והאוויר הקר היה ממלא את הריאות. הייתי נושם את השקט, מאזין לשירת הציפורים, ומרגיש את היום החדש שמתחיל.", 
          
          "הייתה לי הרגל לצפות בזרחת השמש כאשר הייתי טסה למקומות רחוקים. הייתי מתמקדת באור הזהב של השמש שהתפשט על פני האופק. זה היה רגע של שקט ושלווה, שבו הייתי מרגישה את האפשרויות של היום שלפני.", 
          
          "אחד הדברים שאני ממש אוהב לעשות בחופשות הוא לצפות בזרחת השמש על גג המלון. אין דבר יותר מרגיע מאשר לשבת עם כוס קפה ביד, להתבונן בנוף, ולראות איך העולם מתעורר לחיים.", 
          
          "במהלך ההליכה, עצרנו לרגע כדי לצפות בזרחת השמש. האור הראשוני של היום הזהיר את השמיים בצבעים של זהב, ואנחנו ישבנו שם בשקט, מתפללים ליום טוב.", 
          
          "אני מאמין שאין דבר מרגש יותר מ לצפות בזרחת השמש. כאשר האור הראשונים מתחילים להתפשט באופק, אתה מרגיש כאילו אתה חלק ממשהו גדול מאוד. זה מזכיר לי כמה העולם הזה גדול ויפה.", 
          
          "אחת הפעמים המיוחדות ביותר שבהן הזמנתי לצפות בזרחת השמש הייתה בחופשה שלי בהודו. הייתי מתעורר מוקדם, לפני כל העולם, ומשתקף למראה המרהיבה של השמש המתעלה מעל האוקיינוס. זה היה חוויה שאני לעולם לא אשכח.", 
          
          "אני אוהב לצפות בזרחת השמש מהחלון שלי. זה נותן לי את האנרגיה להתחיל את היום. אני אפילו מקדיש כמה דקות בכל בוקר לקחת כוס קפה, לשבת מול החלון, ולהשתקף במראה המדהים הזה.", 
          
          "בראשית, אני אוהב לצפות בזרחת השמש מהמרפסת שלי. זה מזכיר לי את היופי של העולם, את התקווה של יום חדש, ואת החיים הממשיכים להתפתח בכל יום. כל זריחה מציגה תמונה שונה, נוף חדש שממלא אותי בתחושת התרגשות והתפעלות.", 
          
          "היום האחרון שלי ביפן היה יום מיוחד. יצאתי להליך מוקדם בבוקר, כדי לצפות בזרחת השמש מעל הר הפוג'. האור הראשוני של היום מאיר את השיחים המקופים בשלג, מצייר תמונה יפהפיה שאני לעולם לא אשכח.", 
          
          "אחד החוויות המרגשות ביותר שלי היתה לצפות בזרחת השמש מעל הפירמידות במצרים. האור החום החודר את השחקים, מאיר את האבנים העתיקות, ומעניק להם מראה של זהב. זה היה רגע של התבוננות והתפעלות על ההיסטוריה שלנו.", 
          
          "כאשר אני מטייל בים, אני מתכנן לצפות בזרחת השמש מהחוף. אין דבר מרהיב יותר מלראות את האור הראשון של היום מתפשט על גלי הים, משנה את צבעם לגוונים של זהב ואורנג'. זה הופך את החוויה של ההליכה למשהו יוצא דופן.", 
          
          "האלפים היה חלום שלי. כשהגעתי לשם, הייתי עייף אבל מרוצה. לצפות בזרחת השמש מהפסגה, כשהאור העדין של השחר התחיל להתפשט על השפעי השלג הלבנים, היה חוויה בלתי נשכחת. העולם התמלא בנופים שלא ראיתי מעולם. זה היה מרגע של שלווה ושקט, שהיה שווה את כל המאמץ.", 
          
          "אחרי שהוא התעורר מהשנה, איזיק הכין לעצמו כוס קפה והולך להסתובב בגן הפרטי שלו. זו הייתה הדרך האהובה עליו להתחיל את היום - לצפות בזרחת השמש ולשמוע את הציפורים מצפצפות.", 
          
          "את חייבת לצפות בזרחת השמש מהחוף שלנו, אמר יגאל למרים, כאשר הם הגיעו לבית הנופש של המשפחה. זו תחוויה בלתי נשכחת, משהו שתזכורי לעוד שנים.",
          
          "בזמן שהכל בעיר עדיין ישן, רבקה מתעוררת בשעה המוקדמת ביותר שאפשר, מתארגנת, ויוצאת לרוץ. היא אוהבת את השקט של אותן שעות, והמראה של העיר שמתעוררת לחיים. אבל מעל כל, זה הזמן היחיד שהיא יכולה לצפות בזרחת השמש בלי להיות מופרעת.",

          "לשפת האגם הגיעה מיה, המצלמה שלה כבר מוכנה לפעולה. היא התיישבה בשקט, מצפה לרגע הנכון. היא יודעת שממש בקרוב, היא תהיה מסוגלת לצפות בזרחת השמש, והיא רוצה לתפוס את הרגע המושלם בתמונה.", 

          "אחד הדברים המרגשים ביותר בנסיעה לאילת הוא ההזדמנות לצפות בזרחת השמש מעל המדבר. השמים משנים את צורתם מכל הכיוונים, מתוך כך מתמלאים בצבעים רבים, מאוד רומנטי. זהו זמן מיוחד להיות בהם, ולהרגיש את השקט שממלא את האוויר.", 

          "הלכתי לשבת על החוף, מחכה לצפות בזרחת השמש. הים היה שקט ומנוחה, האור הפליד התחיל להתפשט באופק. כשהשמש קמה, היא הפכה את השמים לפריים של צבעים מרהיבים. זה היה רגע של שלווה ושקט, שהגיע לפיקו בזריחה המרהיבה."
]


In [3]:
import torch
from transformers import BertTokenizer, BertModel
from transformers import BertModel, BertTokenizerFast
from transformers import AutoTokenizer, AutoModel 
import transformers
from scipy.spatial import distance_matrix
import gudhi as gd
from gudhi.hera import wasserstein_distance
import numpy as np
import matplotlib.pyplot as plt


def compute_output_model(tokenizer, model, sentence, layer, head):
    # Load pre-trained model

    # Tokenize input and convert to tensor
    inputs = tokenizer(sentence, return_tensors="pt")

    # Forward pass
    # Specify `output_hidden_states=True` when calling the model
    outputs = model(**inputs, output_attentions=True, output_hidden_states=True)

    # Obtain the attention weights
    attentions = outputs.attentions

    # Obtain the attention weights for the specific layer and head
    S = attentions[layer][0, head]

    # Obtain the value vectors
    model.eval()
    with torch.no_grad():
        hidden_states = outputs.hidden_states[layer]
        all_W_v = model.encoder.layer[layer].attention.self.value.weight
        num_heads = model.config.num_attention_heads
        head_dim = model.config.hidden_size // num_heads
        W_v_heads = all_W_v.view(num_heads, head_dim, model.config.hidden_size)
        W_v = W_v_heads[head]
        V = torch.matmul(hidden_states, W_v.t())

    # Compute the output O
    O = torch.matmul(S, V)

    return O



def compute_phrase_distances_and_homology(tokenizer, context_vectors, sentence, phrase):
    # Initialize the tokenizer

    # Tokenize the sentence and the phrase
    sentence_tokens = tokenizer.encode(sentence, add_special_tokens=False)
    phrase_tokens = tokenizer.encode(phrase, add_special_tokens=False)

    # Find the indices of the phrase tokens in the sentence
    phrase_indices = []
    phrase_length = len(phrase_tokens)
    for i in range(len(sentence_tokens) - phrase_length + 1):
        if sentence_tokens[i:i+phrase_length] == phrase_tokens:
            phrase_indices.extend(range(i, i+phrase_length))
            break

    # Extract the context vectors for the phrase
    phrase_context_vectors = context_vectors[0, phrase_indices]

    # Detach the tensor and convert to numpy array
    phrase_context_vectors_np = phrase_context_vectors.detach().numpy()

    # Compute the pairwise Euclidean distances among the phrase context vectors
    distances = distance_matrix(phrase_context_vectors_np, phrase_context_vectors_np)

    # Compute the persistent homology of the distance matrix
    rips_complex = gd.RipsComplex(distance_matrix=distances, max_edge_length=np.max(distances))
    simplex_tree = rips_complex.create_simplex_tree(max_dimension=2)
    persistent_homology = simplex_tree.persistence(min_persistence=0.001)

    return persistent_homology



def transform_persistence_diagram(diagram, target_dimension=0):
    # Only include features of the target dimension and return the transformed diagram
    return [(birth, death) for dimension, (birth, death) in diagram if dimension == target_dimension]



def compute_wasserstein_distances(persistence_diagrams, p=2, target_dimension=0):
    n = len(persistence_diagrams)
    distances = np.zeros((n, n))
    for i in range(n):
        for j in range(i+1, n):
            diagram1 = transform_persistence_diagram(persistence_diagrams[i], target_dimension)
            diagram2 = transform_persistence_diagram(persistence_diagrams[j], target_dimension)
            distance = wasserstein_distance(diagram1, diagram2, order=1., internal_p=2.)
            distances[i, j] = distance
            distances[j, i] = distance
    return distances



def count_negative_entries_below_diagonal(matrix):
    count = 0
    total = 0
    n = len(matrix)
    for i in range(n):
        for j in range(i):
            if matrix[i][j] < 0:
                count += 1
            total += 1
    return count, total

### Compute the context vectors for all layers and heads for the first model

In [4]:
tokenizer = transformers.BertTokenizer.from_pretrained("TurkuNLP/wikibert-base-he-cased")
model = transformers.BertModel.from_pretrained("TurkuNLP/wikibert-base-he-cased", output_attentions=True)

# Get the number of layers and heads in the model
num_layers = model.config.num_hidden_layers
num_heads = model.config.num_attention_heads

context = []
for i in range(len(text)-15):
    sentence_context = []
    for layer in range(num_layers):
        layer_context = []
        for head in range(num_heads):
            layer_context.append(compute_output_model(tokenizer, model, text[i], layer, head))
        sentence_context.append(layer_context)
    context.append(sentence_context)


The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'RobertaTokenizer'. 
The class this function is called from is 'BertTokenizer'.
Some weights of the model checkpoint at TurkuNLP/wikibert-base-he-cased were not used when initializing BertModel: ['cls.predictions.bias', 'cls.predictions.decoder.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializi

### Print the context vectors for the first model for `paragraph`, `layer`, and `head`

In [5]:
paragraph = len(text)-16
layer = 11
head = 11

print(context[paragraph][layer][head].shape)
print(context[paragraph][layer][head])

torch.Size([1, 50, 64])
tensor([[[ 0.1344, -0.0279,  0.0493,  ...,  0.0788,  0.2779,  0.2163],
         [-0.3511, -0.6605,  0.6549,  ...,  0.3316,  1.5600, -0.2835],
         [-0.1105, -0.0528, -0.0322,  ...,  0.3010,  0.6113,  0.3851],
         ...,
         [-0.7663,  0.4865, -0.7388,  ...,  0.2897,  0.0689, -0.1201],
         [ 0.1068, -0.0546,  0.0181,  ...,  0.1291,  0.3789,  0.2001],
         [ 0.1545, -0.0393, -0.0024,  ...,  0.0817,  0.1636,  0.0959]]],
       grad_fn=<CloneBackward0>)


### Compute the context vectors for all layers and heads for the second model

In [6]:
tokenizer_2 = AutoTokenizer.from_pretrained('dicta-il/alephbertgimmel-base')
model_2 = AutoModel.from_pretrained("dicta-il/alephbertgimmel-base", output_attentions=True) 

# Get the number of layers and heads in the model
num_layers = model_2.config.num_hidden_layers
num_heads = model_2.config.num_attention_heads

context_2 = []
for i in range(len(text)-15):
    sentence_context_2 = []
    for layer in range(num_layers):
        layer_context_2 = []
        for head in range(num_heads):
            layer_context_2.append(compute_output_model(tokenizer_2, model_2, text[i], layer, head))
        sentence_context_2.append(layer_context_2)
    context_2.append(sentence_context_2)


Some weights of the model checkpoint at dicta-il/alephbertgimmel-base were not used when initializing BertModel: ['cls.predictions.bias', 'cls.predictions.decoder.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertModel were not initialized from the model checkpoint at dicta-il/alephbertgimmel-base and are newly initialized: ['bert.pooler.dense.bias', 'bert.poole

### Print the context vectors for the second model for `paragraph`, `layer`, and `head`

In [7]:
paragraph = len(text)-16
layer = 11
head = 11

print(context_2[paragraph][layer][head].shape)
print(context_2[paragraph][layer][head])

torch.Size([1, 38, 64])
tensor([[[ 0.0164,  0.0011,  0.0030,  ..., -0.0026,  0.0043, -0.0011],
         [ 0.0409,  0.0460,  0.1011,  ..., -0.0063, -0.0306, -0.0672],
         [ 0.0142,  0.0210,  0.0050,  ..., -0.0190,  0.0122, -0.0507],
         ...,
         [ 0.0208, -0.0019,  0.0166,  ..., -0.0339, -0.0034, -0.0179],
         [ 0.0235, -0.0020,  0.0126,  ..., -0.0097, -0.0027, -0.0107],
         [ 0.0175, -0.0035,  0.0086,  ..., -0.0135,  0.0026, -0.0044]]],
       grad_fn=<CloneBackward0>)


### Compute Persistent Homology of the Keyphrase for the First Model Across All Contexts

Here we compute the persistent homoloy of the keyphrase "לצפות בזרחת השמש" for each context paragraph `text[i]`, for each head of each layer. This will give us one persistence diagram per context, per head of the model. We store the results in `persistent_homology`. 

In [8]:
tokenizer = transformers.BertTokenizer.from_pretrained("TurkuNLP/wikibert-base-he-cased")

# Get the number of layers and heads in the model
num_layers = model.config.num_hidden_layers
num_heads = model.config.num_attention_heads

persistent_homology = []

for i in range(len(text)-15):
    sentence_persistent_homology = []
    for layer in range(num_layers):
        layer_persistent_homology = []
        for head in range(num_heads):
            layer_persistent_homology.append(compute_phrase_distances_and_homology(tokenizer, context[i][layer][head], text[i], "לצפות בזרחת השמש"))
        sentence_persistent_homology.append(layer_persistent_homology)
    persistent_homology.append(sentence_persistent_homology)


The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'RobertaTokenizer'. 
The class this function is called from is 'BertTokenizer'.


In [9]:
paragraph = len(text)-16
layer = 11
head = 11

persistent_homology[paragraph][layer][head]

[(0, (0.0, inf)),
 (0, (0.0, 5.320852064076633)),
 (0, (0.0, 4.669724639887102)),
 (0, (0.0, 4.208814757865532)),
 (0, (0.0, 4.147969554745325))]

### Compute Persistent Homology of the Keyphrase for the Second Model Across All Contexts

Here we compute the persistent homoloy of the keyphrase "לצפות בזרחת השמש" for each context paragraph `text[i]`, for each head of each layer. This will give us one persistence diagram per context, per head of the model. We store the results in `persistent_homology_2`. 

In [10]:
tokenizer_2 = AutoTokenizer.from_pretrained('dicta-il/alephbertgimmel-base')

# Get the number of layers and heads in the model
num_layers = model_2.config.num_hidden_layers
num_heads = model_2.config.num_attention_heads

persistent_homology_2 = []

for i in range(len(text)-15):
    sentence_persistent_homology_2 = []
    for layer in range(num_layers):
        layer_persistent_homology_2 = []
        for head in range(num_heads):
            layer_persistent_homology_2.append(compute_phrase_distances_and_homology(tokenizer_2, context_2[i][layer][head], text[i], "לצפות בזרחת השמש"))
        sentence_persistent_homology_2.append(layer_persistent_homology_2)
    persistent_homology_2.append(sentence_persistent_homology_2)


### Compute Persistence Diagrams for First Model

In [11]:
# Get the number of layers and heads in the model
num_layers = model.config.num_hidden_layers
num_heads = model.config.num_attention_heads

persistence_diagrams = []

for i in range(len(text)-15):
    sentence_persistence_diagrams = []
    for layer in range(num_layers):
        layer_persistence_diagrams = []
        for head in range(num_heads):
            layer_persistence_diagrams.append(persistent_homology[i][layer][head])
        sentence_persistence_diagrams.append(layer_persistence_diagrams)
    persistence_diagrams.append(sentence_persistence_diagrams)

### Compute Persistence Diagrams for Second Model

In [12]:
# Get the number of layers and heads in the model
num_layers = model_2.config.num_hidden_layers
num_heads = model_2.config.num_attention_heads

persistence_diagrams_2 = []

for i in range(len(text)-15):
    sentence_persistence_diagrams_2 = []
    for layer in range(num_layers):
        layer_persistence_diagrams_2 = []
        for head in range(num_heads):
            layer_persistence_diagrams_2.append(persistent_homology_2[i][layer][head])
        sentence_persistence_diagrams_2.append(layer_persistence_diagrams_2)
    persistence_diagrams_2.append(sentence_persistence_diagrams_2)

### Distance Matrices for `layer` and `head` of the first model

In [14]:
# Get the number of layers and heads in the model
num_layers = model.config.num_hidden_layers
num_heads = model.config.num_attention_heads

# Initialize w_distances
w_distances = [[None for _ in range(num_heads)] for _ in range(num_layers)]

for layer in range(num_layers):
    for head in range(num_heads):
        w_distances[layer][head] = compute_wasserstein_distances([persistent_homology[paragraph][layer][head] for paragraph in range(len(text)-15)])



Here we print the Wasserstein distance matrix giving the pairwise Wasserstein distances between each pair of persistence diagrams for the phrase "לצפות בזרחת השמש" in each of the contexts `text[i]` (we have restricted to a particular range of `i` values due to computational limitations). Note here, we have a $7 \times 7$ distance matrix because we have restricted to `len(text)-13` contexts. 

In [15]:
print(w_distances[layer][head].shape)
print(w_distances[layer][head])

(5, 5)
[[0.         1.91550692 5.42725774 3.28734218 6.43482884]
 [1.91550692 0.         3.51175082 1.82834971 4.51932193]
 [5.42725774 3.51175082 0.         2.24399684 1.0075711 ]
 [3.28734218 1.82834971 2.24399684 0.         3.14748666]
 [6.43482884 4.51932193 1.0075711  3.14748666 0.        ]]


### Distance Matrices for `layer` and `head` of the second model


In [16]:
# Get the number of layers and heads in the model
num_layers = model_2.config.num_hidden_layers
num_heads = model_2.config.num_attention_heads

# Initialize w_distances
w_distances_2 = [[None for _ in range(num_heads)] for _ in range(num_layers)]

for layer in range(num_layers):
    for head in range(num_heads):
        w_distances_2[layer][head] = compute_wasserstein_distances([persistent_homology_2[paragraph][layer][head] for paragraph in range(len(text)-15)])


In [17]:
print(w_distances_2[layer][head].shape)
print(w_distances_2[layer][head])

(5, 5)
[[0.         0.41156989 0.30807921 0.53128823 0.3306788 ]
 [0.41156989 0.         0.63907578 0.94285812 0.47170782]
 [0.30807921 0.63907578 0.         0.30378234 0.5869847 ]
 [0.53128823 0.94285812 0.30378234 0.         0.78024975]
 [0.3306788  0.47170782 0.5869847  0.78024975 0.        ]]


### Example of how to use `compute_wasserstein_distances()` with three diagrams

In [18]:
# Example persistence diagrams
diagram1 = [(0, (0.0, np.inf)), (0, (0.0, 0.956513248524484)), (0, (0.0, 0.7576938647389735)), 
            (1, (0.0, np.inf)), (1, (0.0, 0.97)), (2, (0.0, 0.756734))]
diagram2 = [(0, (0.0, np.inf)), (0, (0.0, 1.379910903112847)), (0, (0.0, 1.087934789448628)), 
            (1, (0.0, np.inf)), (1, (0.0, 1.2)), (2, (0.0, 0.85))]
diagram3 = [(0, (0.0, np.inf)), (0, (0.0, 1.379910903112847)), (0, (0.0, 1.08793478)), 
            (1, (0.0, np.inf)), (1, (0.1, 1.2567)), (2, (0.3, 0.775))]

# Compute Wasserstein distances
distances = compute_wasserstein_distances([diagram1, diagram2, diagram3], target_dimension=2)
print(distances)


[[0.         0.093266   0.30055556]
 [0.093266   0.         0.30923292]
 [0.30055556 0.30923292 0.        ]]


### Percentages for Performance Comparison

This next block of code will create a $144 \times 144$ array (or more accurately a $12 \times 12 \times 12 \times 12$ array, since there are $12$ layers with $12$ heads in each layer) to store the percentages indication what percentage of entries of the matrices `w_distances[layer_1][head_1] - w_distances_2[layer_2][head_2]` are negative. Here, we are comparing each head's Wasserstein distances in one model, that is `w_distances[layer_1][head_1]` to each head's Wasserstein distances in a second model, that is `w_distances_2[layer_2][head_2]`. This effectively compares how well the persistent homology is preserved by one `head` in the first model, to how well the persistent homology is preserved by a second `head` in a second model. If the percentage of negative entries is high in the matrix `w_distances[layer_1][head_1] - w_distances_2[layer_2][head_2]`, then the matrix `w_distances_2[layer_2][head_2]` is larger in more places than not, indcating that the second model's Wasserstein distances are higher much more often than the first model's Wasserstein distances. This means the second model is *worse* at preserving persistent homology. On the other hand, if the percentage of the entries in `w_distances[layer_1][head_1] - w_distances_2[layer_2][head_2]` that are negative is low, then the first model's attention head outperforms the second model's attention head at preserving the persistent homology. Doing this for every `head` in every`layer`, w get the $12 \times 12 \times 12 \times 12$ array `percentages`. Querying `percentages` by calling `percentages[layer_1][head_1][layer_2][head_2]` for a heads in specific layers gives us the percentage of entries below the diagonal in `w_distances[layer_1][head_1] - w_distances_2[layer_2][head_2]` that are negative. 

In [19]:
# Create a 4D array to store the percentages
percentages = np.zeros((num_layers, num_heads, num_layers, num_heads))

# Loop over all pairs of layers and heads
for layer_1 in range(num_layers):
    for head_1 in range(num_heads):
        for layer_2 in range(num_layers):
            for head_2 in range(num_heads):
                # Compute the difference of their Wasserstein distance matrices
                matrix = w_distances[layer_1][head_1] - w_distances_2[layer_2][head_2]

                # Count the percentage of negative entries below the diagonal
                negative_count, total_count = count_negative_entries_below_diagonal(matrix)
                percentage = (negative_count / total_count) * 100

                # Store the percentage
                percentages[layer_1, head_1, layer_2, head_2] = percentage

print(percentages.shape)
print("Percentages of negative entries below the diagonal: ", percentages)


(12, 12, 12, 12)
Percentages of negative entries below the diagonal:  [[[[  0.   0.   0. ...   0.   0.   0.]
   [  0.   0.   0. ...   0.   0.   0.]
   [  0.   0.   0. ...   0.   0.   0.]
   ...
   [ 10.   0.   0. ...   0.   0.   0.]
   [  0.   0.   0. ...   0.   0.   0.]
   [ 10.   0.   0. ...   0.   0.  10.]]

  [[  0.  10.   0. ...   0.   0.   0.]
   [ 20.   0.   0. ...  10.   0.  10.]
   [ 10.   0.   0. ...   0.   0.  10.]
   ...
   [ 30.   0.   0. ...   0.   0.   0.]
   [  0.   0.   0. ...   0.   0.   0.]
   [ 40.   0.   0. ...   0.   0.  40.]]

  [[ 10.  10.   0. ...   0.   0.   0.]
   [ 10.   0.   0. ...   0.   0.   0.]
   [ 10.   0.   0. ...   0.   0.  10.]
   ...
   [ 10.   0.   0. ...   0.   0.   0.]
   [  0.   0.   0. ...   0.   0.   0.]
   [ 20.   0.   0. ...   0.   0.  10.]]

  ...

  [[ 10.  10.   0. ...   0.   0.   0.]
   [ 50.   0.   0. ...  10.  40.  30.]
   [ 20.   0.   0. ...   0.   0.  10.]
   ...
   [ 40.   0.  10. ...   0.  20.   0.]
   [  0.  10.   0. ...   0.   0

In [20]:
layer_1 = 11
head_1 = 5

layer_2 = 1
head_2 = 1

print(percentages[layer_1][head_1][layer_2][head_2])

0.0


In [21]:
import numpy as np

# Create a list to store all entries
all_entries = []

# Loop over all entries in the 4D array
for layer_1 in range(num_layers):
    for head_1 in range(num_heads):
        for layer_2 in range(num_layers):
            for head_2 in range(num_heads):
                # Add the entry to the list
                all_entries.append(percentages[layer_1, head_1, layer_2, head_2])

# Convert the list to a numpy array
all_entries = np.array(all_entries)

# Compute the statistics
min_value = np.min(all_entries)
max_value = np.max(all_entries)
mean_value = np.mean(all_entries)
median_value = np.median(all_entries)
std_dev = np.std(all_entries)
percentile_25 = np.percentile(all_entries, 25)
percentile_75 = np.percentile(all_entries, 75)

# Print the statistics
print("Min: ", min_value)
print("Max: ", max_value)
print("Mean: ", mean_value)
print("Median: ", median_value)
print("Standard Deviation: ", std_dev)
print("25th percentile: ", percentile_25)
print("75th percentile: ", percentile_75)



Min:  0.0
Max:  100.0
Mean:  3.7683256172839505
Median:  0.0
Standard Deviation:  10.619195573804737
25th percentile:  0.0
75th percentile:  0.0


From this we can tell that a large majority of the time the second model `dicta-il/alephbertgimmel-base` outperforms the first model `TurkuNLP/wikibert-base-he-cased` at preserving the persistent homology of the phrase "לצפות בזרחת השמש" in the various contexts given by each `text[i]`. 